name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{secrets.DB_URL}}
      DB_PORT: 3306
      DB_USER: ${{secrets.DB_USER}}
      DB_PWRD: ${{secrets.DB_PWRD}}
      PROPERTIES: ${{secrets.properties}}
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install MySQL client
      run: sudo apt-get install mysql-client

    - name: Set env as secret
      env:
        MY_VAL: ${{ secrets.SUPER_SECRET }}
      run: |
        import os
        data = open("file", "w")
        for q in (os.getenv("MY_VAL")):
          print(q)
          data.write(q)
      shell: python
    
    - name: Connect to MySQL
      run: |
        mysql --host="$DB_URL" --port="$DB_PORT" --user="$DB_USER" --password="$DB_PWRD" --protocol=TCP

    - name: Create database and user
      run: |
        mysql -h "$DB_URL" -P "$DB_PORT" -u "$DB_USER" --password="$DB_PWRD" -e "
          CREATE DATABASE IF NOT EXISTS smrt;
          CREATE USER IF NOT EXISTS 'smrt'@'%' IDENTIFIED BY 'smrt';
          GRANT ALL PRIVILEGES ON smrt.* TO 'smrt'@'%';
          FLUSH PRIVILEGES;"

    - name: Setup Environment Variables
      run: echo "$PROPERTIES" > src/main/resources/env.properties

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml
