# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # services:
    #   mysql:
    #     image: mysql:5.7
    #     env:
    #       MYSQL_ROOT_PASSWORD: password
    #     ports:   
    #       - 3306:3306
    #     options: >-
    #       --health-cmd "mysqladmin ping --user=root --password=password --silent"
    #       --health-interval 10s
    #       --health-timeout 10s
    #       --health-retries 5
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: My first action
      env:
          DB_HOST: ${{ secrets.DB_URL }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PWRD: ${{ secrets.DB_PWRD }}
          DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        echo DB_HOST
        echo DB_PORT
        echo DB_USER
        echo DB_PWRD
        echo DB_NAME
    
    - name: Install MySQL client
      run: sudo apt-get install mysql-client
              
    - name: Connect to MySQL
      run: |
          # mysql --host=`${{ secrets.DB_URL }}` --port=`${{ secrets.DB_PORT }}` --user=`${{ secrets.DB_USER }}` --password=`${{ secrets.DB_PWRD }}` `${{ secrets.DB_NAME }}`

    - name: Create database and user
      run: |
          mysql -h "${{ secrets.DB_URL }}" -u "${{ secrets.DB_USER }}" --password="${{ secrets.DB_PWRD }}" -e "
            CREATE DATABASE IF NOT EXISTS smrt;
            CREATE USER 'smrt'@'%' IDENTIFIED BY 'smrt';
            GRANT ALL PRIVILEGES ON smrt.* TO 'smrt'@'%';
            FLUSH PRIVILEGES;"
    - uses: actions/checkout@v3
    - name: Setup Environment Variables
      run: |
        echo "${{ secrets.properties }}" > src/main/resources/env.properties
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
