name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: root
          # options:
          #   ---health-cmd "mysqladmin ping --user=root --password=password --silent"--health-interval 10s--health-timeout 10s--health-retries 5
    runs-on: ubuntu-latest
    environment: env
    env:
      DB_URL: ${{secrets.DB_URL}}
      DB_PORT: ${{secrets.DB_PORT}}
      DB_USER: ${{secrets.DB_USER}}
      DB_PWRD: ${{secrets.DB_PWRD}}
      PROPERTIES: ${{secrets.properties}}
      # MYSQL_ROOT_PASSWORD: password
      
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install MySQL client
      run: sudo apt-get install mysql-client
    
    - name: Connect to MySQL
      run: |
        sudo systemctl start mysql
        sudo mysql --host="127.0.0.1" --port="3306" --user="root" --password="root" --protocol=TCP

    - name: Create database and user
      run: |
        mysql -h "127.0.0.1" -P "3306" -u "root" --password="root" -e "
          CREATE DATABASE IF NOT EXISTS smrt;
          CREATE USER IF NOT EXISTS 'smrt'@'localhost' IDENTIFIED BY 'smrt';
          GRANT ALL PRIVILEGES ON smrt.* TO 'smrt'@'localhost';
          FLUSH PRIVILEGES;"
        mysql -h "127.0.0.1" -P "3306" -u "root" --password="root" -e "
          SELECT user, host FROM mysql.user;
        "

    - name: Setup Environment Variables
      run: |
        echo "$PROPERTIES" > src/main/resources/env.properties

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml
